-- This file was auto-generated by diesel CLI

CREATE TABLE products (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(500) NOT NULL,
    description TEXT NOT NULL,
    category VARCHAR(200) NOT NULL,
    price DECIMAL(15, 2),
    currency VARCHAR(10),
    features JSONB NOT NULL DEFAULT '[]',
    specifications JSONB NOT NULL DEFAULT '{}',
    image_urls JSONB NOT NULL DEFAULT '[]',
    is_active BOOLEAN NOT NULL DEFAULT true,
    metadata JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_products_category ON products(category);
CREATE INDEX idx_products_is_active ON products(is_active);
CREATE INDEX idx_products_price ON products(price);
CREATE INDEX idx_products_name ON products USING gin(to_tsvector('english', name));
CREATE INDEX idx_products_features ON products USING gin(features);
CREATE INDEX idx_products_metadata ON products USING gin(metadata);

CREATE TABLE brochures (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title VARCHAR(500) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    file_name VARCHAR(500) NOT NULL,
    file_url TEXT NOT NULL,
    file_type VARCHAR(50) NOT NULL,
    file_size_bytes BIGINT NOT NULL DEFAULT 0,
    product_ids JSONB NOT NULL DEFAULT '[]',
    category VARCHAR(200) NOT NULL DEFAULT '',
    language VARCHAR(10) NOT NULL DEFAULT 'th',
    is_public BOOLEAN NOT NULL DEFAULT true,
    download_count BIGINT NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_brochures_category ON brochures(category);
CREATE INDEX idx_brochures_file_type ON brochures(file_type);
CREATE INDEX idx_brochures_language ON brochures(language);
CREATE INDEX idx_brochures_is_public ON brochures(is_public);
CREATE INDEX idx_brochures_product_ids ON brochures USING gin(product_ids);

CREATE TABLE company_info (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    key VARCHAR(100) UNIQUE NOT NULL,
    value TEXT NOT NULL,
    category VARCHAR(100) NOT NULL DEFAULT 'general',
    language VARCHAR(10) NOT NULL DEFAULT 'th',
    metadata JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_company_info_key ON company_info(key);
CREATE INDEX idx_company_info_category ON company_info(category);

CREATE TABLE faqs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    category VARCHAR(200) NOT NULL DEFAULT 'general',
    language VARCHAR(10) NOT NULL DEFAULT 'th',
    is_active BOOLEAN NOT NULL DEFAULT true,
    view_count BIGINT NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_faqs_category ON faqs(category);
CREATE INDEX idx_faqs_language ON faqs(language);
CREATE INDEX idx_faqs_is_active ON faqs(is_active);

CREATE TABLE product_brochures (
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    brochure_id UUID NOT NULL REFERENCES brochures(id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, brochure_id)
);

CREATE TRIGGER update_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_brochures_updated_at
    BEFORE UPDATE ON brochures
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_company_info_updated_at
    BEFORE UPDATE ON company_info
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_faqs_updated_at
    BEFORE UPDATE ON faqs
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

INSERT INTO agents (id, name, description, model, preamble, temperature, top_k_documents, tools)
VALUES (
    'sales-agent',
    'Sales Agent',
    'AI assistant for sales support and product recommendations',
    'gpt-4',
    'You are a helpful sales assistant.',
    0.7,
    5,
    '["product_search", "get_brochure", "company_info"]'
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tools = EXCLUDED.tools;
