DROP TRIGGER IF EXISTS update_faqs_updated_at ON faqs;
DROP TRIGGER IF EXISTS update_company_info_updated_at ON company_info;
DROP TRIGGER IF EXISTS update_brochures_updated_at ON brochures;
DROP TRIGGER IF EXISTS update_products_updated_at ON products;
DELETE FROM agents WHERE id = 'sales-agent';
DROP TABLE IF EXISTS product_brochures;
DROP TABLE IF EXISTS faqs;
DROP TABLE IF EXISTS company_info;
DROP TABLE IF EXISTS brochures;
DROP TABLE IF EXISTS products;
